server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
      username: root
      password: root
      url: jdbc:mysql://localhost:3308/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  thymeleaf:
    mode: HTML5
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  config-location: classpath:mybatis-cofig.xml

#分页插件配置
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

